"""add_promo_code_to_promoactivation

Revision ID: 1e1e63431b14
Revises: a44c781b1250
Create Date: 2025-08-26 23:45:19.643323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e1e63431b14'
down_revision: Union[str, Sequence[str], None] = 'a44c781b1250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booster_accounts', sa.Column('balance_usd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booster_accounts', 'balance_usd')
    # ### end Alembic commands ###
