"""добавил_поле_active_discount_percent_в_user

Revision ID: 35111ab83673
Revises: f1234567890a
Create Date: 2025-07-30 00:17:27.287722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35111ab83673'
down_revision: Union[str, Sequence[str], None] = 'f1234567890a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_discount_percent', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active_discount_percent')
    # ### end Alembic commands ###
