"""add_promo_code_to_promoactivation

Revision ID: a44c781b1250
Revises: d1d47fe3944e
Create Date: 2025-08-23 23:26:53.986355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a44c781b1250'
down_revision: Union[str, Sequence[str], None] = 'd1d47fe3944e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo_activations', sa.Column('promo_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promo_activations', 'promo_code')
    # ### end Alembic commands ###
