"""описание изменений

Revision ID: c5274a6d45fe
Revises: c38dde276f40
Create Date: 2025-07-07 16:50:14.681055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5274a6d45fe'
down_revision: Union[str, Sequence[str], None] = 'c38dde276f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('bonus_balance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bonus_balance')
    op.drop_column('users', 'balance')
    # ### end Alembic commands ###
