"""добавил мультивалютные балансы бустеров

Revision ID: f1234567890a
Revises: ed0d3944bd99
Create Date: 2025-01-23 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1234567890a'
down_revision = 'ed0d3944bd99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем новые колонки для мультивалютных балансов
    op.add_column('booster_accounts', sa.Column('balance_kg', sa.Float(), nullable=True))
    op.add_column('booster_accounts', sa.Column('balance_kz', sa.Float(), nullable=True))
    op.add_column('booster_accounts', sa.Column('balance_ru', sa.Float(), nullable=True))
    
    # Переносим данные из старого balance в balance_ru (по умолчанию рубли)
    op.execute("UPDATE booster_accounts SET balance_kg = 0, balance_kz = 0, balance_ru = COALESCE(balance, 0)")
    
    # Устанавливаем NOT NULL и значения по умолчанию
    op.alter_column('booster_accounts', 'balance_kg', nullable=False, server_default='0')
    op.alter_column('booster_accounts', 'balance_kz', nullable=False, server_default='0')
    op.alter_column('booster_accounts', 'balance_ru', nullable=False, server_default='0')
    
    # Удаляем старую колонку balance
    op.drop_column('booster_accounts', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Возвращаем старую колонку balance
    op.add_column('booster_accounts', sa.Column('balance', sa.Float(), nullable=False, server_default='0'))
    
    # Переносим данные из balance_ru обратно в balance
    op.execute("UPDATE booster_accounts SET balance = COALESCE(balance_ru, 0)")
    
    # Удаляем новые колонки
    op.drop_column('booster_accounts', 'balance_ru')
    op.drop_column('booster_accounts', 'balance_kz')
    op.drop_column('booster_accounts', 'balance_kg')
    # ### end Alembic commands ###
